input_file_path = '/Users/colinclapham/github/baseball-data-project/baseball_data_project/inputs'

output_file_path = '/Users/colinclapham/github/baseball-data-project/baseball_data_project/deliverables'

data_years = [
    2023
]